export const JWT_ACCESS_TOKEN_STRATEGY = 'JWT_ACCESS_TOKEN_STRATEGY';
export const JWT_REFRESH_TOKEN_STRATEGY = 'JWT_REFRESH_TOKEN_STRATEGY';
export const API_KEY_STRATEGY = 'API_KEY_STRATEGY';

export const API_KEY_HEADER = 'x-api-key';
